import Head from "next/head";
import { NavBar } from "@/libs/feature/nav-bar/NavBar";
import { SearchBar } from "@/libs/feature/search-bar/SearchBar";
import { Box, Container } from "@mui/material";

export default function Home() {
  return (
    <Box minHeight="100vh" flexDirection="column">
      <Head>
        <title>Factimal</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <Box paddingTop={5}>
        <Container>
          <SearchBar />
        </Container>
      </Box>
    </Box>
  );
}
